### ISSUE TITLE
refine `region` parameter

### ISSUE THREAD

**Issue by opeeters** [irceline/opendataviewer#3]
See e.g.:
https://www.irceline.be/opendataviewer/index.html?lang=en&pollutant=pm25&resolution=rioifdm&interval=hmean&region=vl&lang=en

There should be a `cql_filter` should be added to the station layer request e.g.:
```
cql_filter: "network = 'Flanders'",
```
Alternatives:
* Wallonia

For `region=br` show all for the time being.

Also the `fitBounds` should be adjusted to the contours of the region being selected.

**Comment by stevenvdbosch** [comment]
Fitted bounds to region.

**Comment by stevenvdbosch** [comment]
@opeeters 
I fitted bounds for Flanders, Wallonia and Brussels
=> Did you also wanted this last one?

I also added the station cql_filter. (not in case of Brussels)

=> one thing i saw was when i filtered on 'br', the interpolated layer was gone. Is this normal? 
I guess there exists no "rioifdm:no2_hmean_br" layer as such (this is a var in the interpolatedWmsOptions , line 179 )

**For me this branch can be merged with the master**

**Comment by opeeters** [comment]
@stevenvdbosch 
`rioifdm:no2_hmean_br` is indeed still missing. Let's just zoom to region Brussels and use the unfiltered station layer and `rioifdm:no2_hmean`. 
But do add a case specific to `region=br`. We might add a clip later. At the moment this does not yet seem necessary..

**Comment by opeeters** [comment]
@stevenvdbosch 
Sorry, I think this already as it should be. I did not see your last commit..

**Comment by opeeters** [comment]
OK, zoom and station layer are fine, just add the uncliped rioifdm to case `br`..

**Comment by stevenvdbosch** [comment]
Ok, done. @opeeters

**Comment by opeeters** [comment]
Thanks!
