### ISSUE TITLE
Leaflet Control for better navigating in time

### ISSUE THREAD

**Issue by amotl** [irceline/opendataviewer#8]
Dear @opeeters, @d-roet and @stevenvdbosch,

the other day, we stumbled upon the [`Leaflet.TimeDimension`](https://community.panodata.org/t/leaflet-timedimension/154) component. Coming back here, we wanted to quickly share that with you.

When everything fits together well, this component could further improve navigating the time domain in the spirit of #7.

With kind regards,
Andreas.

cc @wetterfrosch

**Comment by opeeters** [comment]
merged into `master` cf 79e109b4a9780960750462f647b8d92d5235d146

**Comment by amotl** [comment]
This is a different thing than #7. It is a note about the Leaflet.TimeDimension component. Please reject or reopen.
